version: "3.4"
services:
  postgres:
    networks:
      - dbstack
    image: postgres:14-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      Postgres_DB: "postgres"
    ports:
     - 0.0.0.0:54320:5432
    volumes:
      - ./postgres.local:/var/lib/postgresql/data

networks:
  dbstack:
